GEMINI_API_KEY = ""
LOGFIRE_TOKEN = ""

[auth]
redirect_uri = ""
cookie_secret = ""
admin_emails = [""]

[auth.google]
client_id = ""
client_secret = ""
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[connections.gsheets]
spreadsheet = ""
type = "service_account"
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = ""
